name: ott_platform_task
description: "ott_platform_task"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.2.0
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  fpdart: ^1.1.0
  shared_preferences: ^2.5.3
  flutter_bloc: ^8.1.3
  injectable: ^2.1.2
  connectivity_plus: ^6.1.4
  go_router: ^15.1.2
  cached_network_image: ^3.2.3
  carousel_slider: ^5.1.1
  video_player: ^2.5.0
  chewie: ^1.7.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  injectable_generator: ^2.1.5
  build_runner: ^2.4.6
  bloc_test: ^9.1.7
  mocktail: ^1.0.3

flutter:


  uses-material-design: true

  assets:
    - assets/icons/